### ISSUE TITLE
Can you add a login and comments section?

### ISSUE THREAD

**Issue by Ratdevils** [itzzzme/zenime#1]
I loved your project! It’s smooth and well-executed. To make it even more stable and faster, consider adding Redis caching. Also, the proxy API is currently visible in the network inspector—hiding it could enhance security.

Additionally, it would be great to see comments and a login modal implemented in the future. Best of luck, and thanks

**Comment by itzzzme** [comment]
as for the caching data, the API I am using is also created by me and all data returned by the API is cached through database so I don't need to implement it on website as for now

**Comment by Ratdevils** [comment]
Thanks for clarifying! I wanted to ask about the .env variables VITE_TOTAL_WORKER_URL and VITE_WORKER_URL—what URLs or APIs should go here?

Also, for the Anime API, which caching are you using in CACHE_URL, and what should this be set to?

**Comment by itzzzme** [comment]
in VITE_TOTAL_WORKER_URL you have to put total no. of workers you are using (which is an integer)
and IN VITE_WORKER_URL you have to put worker's url seperated by commas(,)

for CACHE_URL it's currently private but the cache_server use google's firestore to store cache data as for now
so for CACHE_URL it should be set to the entry point of the cache server

**Comment by Ratdevils** [comment]
Hey, I hope you are doing well. I wanted to share some suggestions.

1. Maybe Highlight the filler episodes so people know what they can skip.
2. Could be cool if the header hid when scrolling down and popped back up when scrolling up—just makes it easier to browse.

Also, for security, could you hide the API routes/URLs and protect them? Right now, both the anime API and proxy API show up in the network tab when inspecting. I noticed you updated the proxy API to only allow whitelisted access—could you apply that to the anime API too? Ideally, it’d be great if the APIs didn’t show up at all, like on sites like Hianime where the APIs aren’t visible.

**Comment by itzzzme** [comment]
you can check the website now filler highlight is added in episodes

and as per fundamentals of networking you can't hide the requests you are making in you network tab. you can't see any dedicated api in hianime website because they don't use any REST api instead they use ajax requsts to fetch their datas. and it's visible on the network tab if you see carefully since it's not fundamentally possible to hide those requests made by the website from network tab.

Additionally, my backend API has CORS policies in place. This ensures that if an unauthorized third party attempts to access it via their frontend, they will encounter an error due to CORS restrictions, such as the "Access-Control-Allow-Origin blocked" response.

**Comment by Ratdevils** [comment]
Cool, I didn’t know about that, sorry about the misunderstanding! Thanks for the detailed explanation.

As for the site, the loading speed is a bit slow, but I think that’s because of hianime that site is also slow.

The only thing left to make it perfect, in my opinion, is adding a login and comment section!

 I really appreciate you considering my suggestions.

**Comment by itzzzme** [comment]
yeah it's little bit slow for first few response but in future I am planning to host the api on paid plans

**Comment by Ratdevils** [comment]
I think adding redis as optional will make it a bit faster. The local caching for the main site is slow. 

I used redis in the anime api of yours, that was a little bit faster. I love redis.

**Comment by Ratdevils** [comment]
Can you add the continue watching. There’s also promotion videos in the anime info page. Auto next in the watch page.

**Comment by itzzzme** [comment]
Currently these are one my TODO list, so this will come in future once I am out of my tight schedule

**Comment by Ratdevils** [comment]
Oh, thanks.

**Comment by Ratdevils** [comment]
Hi, I hope you’re doing well. Could you add the Consumet API as an alternative for streaming anime episodes? Currently, the site relies entirely on Hianime, so if they make any changes, the whole site stops working. Having 1-2 backup sources would prevent this issue, especially for streaming.

**Comment by itzzzme** [comment]
> Hi, I hope you’re doing well. Could you add the Consumet API as an alternative for streaming anime episodes? Currently, the site relies entirely on Hianime, so if they make any changes, the whole site stops working. Having 1-2 backup sources would prevent this issue, especially for streaming.

Thanks for the suggestion. Taken into consideration
