### ISSUE TITLE
Page not found error

### ISSUE THREAD

**Issue by PacaHat** [itzzzme/zenime#2]
Besides the homepage, every other page shows the same issue after a refresh. I get a "Page Not Found" error.

At first, I thought it might be caused by Vercel, so I switched to Netlify, but the issue persists.

![Screenshot_2024-11-29-14-57-41-91](https://github.com/user-attachments/assets/3abac1e3-300f-4223-a1b0-30fd6916deee)

**Comment by itzzzme** [comment]
see the errors in console and also provide some more screenshots of what page are you trying to access. Because it's handled in my code so it should not show the default 404 page of netlify. If you did something wrong while configuring then also it will show the customised `/404-not-found-page` in the website

**Comment by PacaHat** [comment]
https://pnime.vercel.app/

You can visit this website all things works perfectly fine  like streaming, anime search+ details page but if you refresh for onece it will show this error and you have to re-visit the homepage
 it's maybe because of caches error or I haven't setup the env properly I am not sure 🙃


To see the error :- just visit the website click on any anime after it loads the player page or details page hit refresh

**Comment by PacaHat** [comment]
https://pnime.vercel.app/

You can visit this website all things works perfectly fine like streaming, anime search+ details page but if you refresh for onece it will show this error and you have to re-visit the homepage
it's maybe because of caches error or I haven't setup the env properly I am not sure 🙃

To see the error :- just visit the website click on any anime after it loads the player page or details page hit refresh

**Comment by itzzzme** [comment]
check your vercel logs. Usually this type of error should not occur even though you didn't setup env or cache. You don't have to mandatorily setup cache you will get no error for that. But I will suggest to check your vercel logs

**Comment by PacaHat** [comment]
![image](https://github.com/user-attachments/assets/9251bf52-4c31-4135-a7f4-6ae8167e1ee5)
.

**Comment by PacaHat** [comment]
but in my localost its working just fine with no errors

**Comment by itzzzme** [comment]
Then I don't think there is anything wrong in the code maybe try deploying the website with different account in vercel

**Comment by PacaHat** [comment]
Ok
