### ISSUE TITLE
Streaming error/ video not playing 

### ISSUE THREAD

**Issue by uncooldude** [itzzzme/zenime#3]
Hi there devs,
I was looking into your very cool project and I did try it and for some reason the anime video is not playing, Please help me out

**Comment by itzzzme** [comment]
Check it now. It should be fixed

**Comment by uncooldude** [comment]
@itzzzme I mean yeah, it is working on your deployment, but idk why it's not working on my deployment (I have synced the fork)
So first thing first,
I tried deoploying using vercel and it failed due to some reason (Please tell me how to deploy if possible, even a hint is fine)
so I decided to locally host it just to check, where it worked and build was sucessful but still there is no VIDEO PLAYBACK

if u help me out, it would be very great
Thanks have a good day

**Comment by itzzzme** [comment]
did you also deploy the m3u8 proxy server. Because If you don't deploy you may counter cors error and video will not deploy. So I recommend take a look into console for error.

**Comment by uncooldude** [comment]
I was looking into it and can u help me with what is allowed origin,
it would be better if I can get your discord or telegram to contact you
Sorry, i'm new into streaming websites

**Comment by itzzzme** [comment]
If you are deploying m3u8 server then you have to put you website's link into the allowed origin array of m3u8 proxy server

**Comment by uncooldude** [comment]
can u just send a picture of how do you deploy this on vercel or cloudflare pages, that would be too helpful

**Comment by uncooldude** [comment]
Also if you don't mind, which file do we need to edit to change the css color?, pink looks a lil weird you know 😅

**Comment by uncooldude** [comment]
> > can u just send a picture of how do you deploy this on vercel or cloudflare pages, that would be too helpful, Edit 1: I managed to deploy it on cloudflare pages Please help me out with api and the proxy, I mean should I put this address into the allowed origin
> > Edit 2: I got the video playback and also get to something, which I don't get, the m3u8 server was causing the issue, as when I removed it from my .env I got my video playback, Thanks man your project is real good, keep up!
> 
> you are not getting the CORS error for some videos because some of the hls streaming does not implement cors that's why. But when you try to use those streams with CORS implemented then you will get the error. So to make all servers working you need to deploy the m3u8 proxy server
> 
> In allowed origin of m3u8 proxy server refer `.env.example` (given in https://github.com/itzzzme/m3u8proxy) file to know everything you need to. Just a thing that in allowed origin you have to add those deploy links on which website you need to use the proxy server. also to deploy the api server you can refer the docs and `.env.example`( given in https://github.com/itzzzme/anime-api)


Noted Thanks for help man, keep it up! 
just a last thing, if you don't mind, which file do we need to edit to change the css color?, pink looks a lil weird you know 😅

**Comment by uncooldude** [comment]
There is no playback again, not just on my instance but on your (zenime,site) website aswell

**Comment by itzzzme** [comment]
> There is no playback again, not just on my instance but on your (zenime.site) website aswell

Yes. That's the problem of the API. since the source also changed It's not giving a correct response. Will get fixed very soon. Thanks for raising the issue

**Comment by uncooldude** [comment]
> > There is no playback again, not just on my instance but on your (zenime.site) website aswell
> 
> Yes. That's the problem of the API. since the source also changed It's not giving a correct response. Will get fixed very soon. Thanks for raising the issue

No Problem, happy knowing I helped you in any ways. Please do let me know when it's fixed

**Comment by itzzzme** [comment]
@uncooldude site is back. Check it out

**Comment by uncooldude** [comment]
> @uncooldude site is back. Check it out

cooll, imma check, thanks for ur hardwork man, ur crazy

**Comment by uncooldude** [comment]
@itzzzme Just requesting a feature, Please add continue watching feature

**Comment by itzzzme** [comment]
> @itzzzme Just requesting a feature, Please add continue watching feature

@uncooldude thanks for the suggestion. Noted!

**Comment by itzzzme** [comment]
> @itzzzme Just requesting a feature, Please add continue watching feature

@uncooldude thanks for the suggestion. Noted!

**Comment by itzzzme** [comment]
> > > [@itzzzme](https://github.com/itzzzme) Just requesting a feature, Please add continue watching feature
> > 
> > [@uncooldude](https://github.com/uncooldude) thanks for the suggestion. Noted!
> 
> No problem, I have one more suggestion, you can add manga as well using anilist api, you can ask me for help if u need it

@uncooldude sure
