### ISSUE TITLE
Streaming link is broken 

### ISSUE THREAD

**Issue by PacaHat** [itzzzme/zenime#4]
Streaming api response isn't showing any streaming link 

{
  "success": true,
  "results": {
    "streamingLink": [
      {
        "id": "578153",
        "type": "dub",
        "link": [],
        "tracks": [],
        "server": "HD-1"
      },
      {
        "id": "52961",
        "type": "dub",
        "link": [],
        "tracks": [],
        "server": "HD-2"
      },

**Comment by itzzzme** [comment]
@PacaHat site is back. Check it out
