### ISSUE TITLE
Help in settting site up 

### ISSUE THREAD

**Issue by Gupta507** [itzzzme/zenime#5]
Hi @itzzzme,

I hope you're doing well! I'm currently having some trouble with setting up the reverse proxy and proxy during my site deployment. I was wondering if you could create a video tutorial on this topic?

Your help would be greatly appreciated, and by the way, the site is absolutely awesome—great work!

Looking forward to your response.

**Comment by itzzzme** [comment]
> Hi @itzzzme,
> 
> I hope you're doing well! I'm currently having some trouble with setting up the reverse proxy and proxy during my site deployment. I was wondering if you could create a video tutorial on this topic?
> 
> Your help would be greatly appreciated, and by the way, the site is absolutely awesome—great work!
> 
> Looking forward to your response.

@Gupta507 You can refer to this https://github.com/itzzzme/zenime/blob/main/.env.example. I have explained everything to setup the proxy servers
